#Defines the port at which config server ise running so that rest of the services can pick up their external configurations
server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hashiDrama/microservices-config.git
          searchPaths: MASTER